#!/bin/sh

APE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/bin/"

if [ ! -f ${APE_PATH}running.pid ]; then
	APE_PID=
else
	APE_PID=`cat ${APE_PATH}running.pid`
fi

if [ ! $APE_PID ]; then

	echo "Starting APE server [DEBUG]..."
	cd $APE_PATH
	./ApeServer --cfg debug.conf

else
	if ps -p $APE_PID > /dev/null 
	then
		echo "The APE Server is currently running..."
		./stop
		sleep 2
	fi
	
	echo "Starting APE server [DEBUG]..."
	cd $APE_PATH
       	./ApeServer --cfg debug.conf
	
fi
