#!/bin/bash

APE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/bin/"

if [ -f "INSTANCE" ]; then
	APE_INSTANCE=`cat ./INSTANCE`
else
	APE_INSTANCE="ApeServer"
fi

if [ ! -f ${APE_PATH}running.pid ]; then
	APE_PID=
else
	APE_PID=`cat ${APE_PATH}running.pid`
fi

if [ ! $APE_PID ]; then

	echo Starting APE server...
	cd $APE_PATH
	# echo APE server running...
	./${APE_INSTANCE}

else
	if ! ps -p $APE_PID > /dev/null  
	then
		echo No proccess with PID $APE_PID.
		# Remove the PID file
		rm -rf ${APE_PATH}running.pid
		
		# Start the server
		echo Starting APE server...
	        cd $APE_PATH
       		# echo APE server running...
	        ./${APE_INSTANCE}
	else
		echo APE server already running...
	fi
fi
