#!/bin/bash

APE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/bin/"

if [ -f ${APE_PATH}running.pid ]; then
	APE_PID=`cat ${APE_PATH}running.pid`
else
	APE_PID=
fi

if [ ! $APE_PID ]; then

	echo APE Server is not running

else
	kill $APE_PID
	echo Killing APE Server with PID $APE_PID
fi
